const images = {
  logoBGWhite: require("../images/logoBGWhite.png"),
  logoRemoveBg: require("../images/logo-removebg.png"),
  bGroundAcc: require("../images/backgroundaccount.jpg"),
  platFormOnPc: require("../images/platFormOnPc.png"),
  platFormOnMobile: require("../images/platFormOnMobile.png"),
  emailLogo: require("../images/gmailLogo.png"),
  gmailLogo: require("../images/gmailLogo2.png"),
  zaloLogo: require("../images/zaloIcon.png"),
  instaLogo: require("../images/instaLogo.png"),
  roadYo: require("../images/roadYo.png"),
  appYo: require("../images/AppYo.png"),
  webAndApp: require("../images/Web&App.png"),
  car: require("../images/car.png"),
  foodDelivery: require("../images/Food.png"),
  meatDelivery: require("../images/Meat.png"),
  groceryDelivery: require("../images/Grocery.png"),
  healtDelivery: require("../images/Healt.png"),
  commmerceDelivery: require("../images/Commmerce.png"),
  nowFood: require("../images/nowFood.jpg"),
  goFood: require("../images/goFood.png"),
  groceryFeature: require("../images/groceryFeature.png"),
  lhLogo: require("../images/lhLogo.png"),
  nikeLogo: require("../images/nikeLogo.png"),
  featureImg1: require("../images/Blog/featureImg1.png"),
  bannerLogin: require("../images/bannerLogin.png"),
  logoAgri: require("../images/logoAgri.png"),
};

export default images;
